development:
  address: "smtp.mailgun.org"
  port: "587"
  domain: <%=ENV['DOMAIN']%>
  authentication: "plain"
  user_name: <%=ENV['GMAIL_USERNAME']%>
  password: <%=ENV['GMAIL_PASSWORD']%>
  enable_starttls_auto: true